### ISSUE TITLE
Sound setting is ignored

### ISSUE THREAD

**Issue by alexwalterbos** [wouter-willems/6seasons#1]
OnePlus 3T Android 7.1.1
The game still plays audio, though softly, when the sound is switched off

**Comment by wouter-willems** [comment]
Is this still an issue with the new build?

**Comment by alexwalterbos** [comment]
Nope, this one is fixed! Sweet audio btw, but could it be that I've only hear rain so far? (Up to challenge 10)

**Comment by wouter-willems** [comment]
yes work in progress
