### ISSUE TITLE
Timing of explosions

### ISSUE THREAD

**Issue by alexwalterbos** [wouter-willems/6seasons#4]
After the initial three hexagons explode, the chain seems to be delayed maybe a third of a second before the chain starts. Especially in shorter chains of 4 or 5 total hexagons, this seems a bit laggy. If deliberate, you might want to remove that delay?

**Comment by wouter-willems** [comment]
This is indeed deliberate, i was already doubting if that delay was right, this confirms the issue. Will look at this

**Comment by wouter-willems** [comment]
fixed it
